// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: arquivos.sql

package postgres

import (
	"context"
)

const getArquivo = `-- name: GetArquivo :one
SELECT hash, storage_key, content_type, tamanho_bytes, criado_em
FROM arquivos
WHERE hash = $1
`

func (q *Queries) GetArquivo(ctx context.Context, hash string) (Arquivo, error) {
	row := q.db.QueryRow(ctx, getArquivo, hash)
	var i Arquivo
	err := row.Scan(
		&i.Hash,
		&i.StorageKey,
		&i.ContentType,
		&i.TamanhoBytes,
		&i.CriadoEm,
	)
	return i, err
}

const saveArquivo = `-- name: SaveArquivo :exec
INSERT INTO arquivos (hash, storage_key, content_type, tamanho_bytes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (hash) DO NOTHING
`

type SaveArquivoParams struct {
	Hash         string
	StorageKey   string
	ContentType  string
	TamanhoBytes int64
}

func (q *Queries) SaveArquivo(ctx context.Context, arg SaveArquivoParams) error {
	_, err := q.db.Exec(ctx, saveArquivo,
		arg.Hash,
		arg.StorageKey,
		arg.ContentType,
		arg.TamanhoBytes,
	)
	return err
}

const getDocumentoAnexo = `-- name: GetDocumentoAnexo :one
SELECT id_protocolo, hash, baixado_em
FROM documentos_anexo
WHERE id_protocolo = $1
`

func (q *Queries) GetDocumentoAnexo(ctx context.Context, idProtocolo int64) (DocumentoAnexo, error) {
	row := q.db.QueryRow(ctx, getDocumentoAnexo, idProtocolo)
	var i DocumentoAnexo
	err := row.Scan(
		&i.IDProtocolo,
		&i.Hash,
		&i.BaixadoEm,
	)
	return i, err
}

const saveDocumentoAnexo = `-- name: SaveDocumentoAnexo :exec
INSERT INTO documentos_anexo (id_protocolo, hash, baixado_em)
VALUES ($1, $2, CURRENT_TIMESTAMP)
ON CONFLICT (id_protocolo) DO UPDATE SET
    hash = EXCLUDED.hash,
    baixado_em = EXCLUDED.baixado_em
`

type SaveDocumentoAnexoParams struct {
	IDProtocolo int64
	Hash        string
}

func (q *Queries) SaveDocumentoAnexo(ctx context.Context, arg SaveDocumentoAnexoParams) error {
	_, err := q.db.Exec(ctx, saveDocumentoAnexo, arg.IDProtocolo, arg.Hash)
	return err
}
