// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: arquivos.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const getArquivo = `-- name: GetArquivo :one
SELECT id, hash_sha256, chave_storage, mime_type, tamanho_bytes, criado_em FROM arquivos WHERE id = $1
`

func (q *Queries) GetArquivo(ctx context.Context, id int64) (Arquivo, error) {
	row := q.db.QueryRow(ctx, getArquivo, id)
	var i Arquivo
	err := row.Scan(
		&i.ID,
		&i.HashSHA256,
		&i.ChaveStorage,
		&i.MimeType,
		&i.TamanhoBytes,
		&i.CriadoEm,
	)
	return i, err
}

const getArquivoByHashSHA256 = `-- name: GetArquivoByHashSHA256 :one
SELECT id, hash_sha256, chave_storage, mime_type, tamanho_bytes, criado_em FROM arquivos WHERE hash_sha256 = $1
`

func (q *Queries) GetArquivoByHashSHA256(ctx context.Context, hashSha256 []byte) (Arquivo, error) {
	row := q.db.QueryRow(ctx, getArquivoByHashSHA256, hashSha256)
	var i Arquivo
	err := row.Scan(
		&i.ID,
		&i.HashSHA256,
		&i.ChaveStorage,
		&i.MimeType,
		&i.TamanhoBytes,
		&i.CriadoEm,
	)
	return i, err
}

const getArquivoConteudo = `-- name: GetArquivoConteudo :one
SELECT id, arquivo_id, metodo, formato, conteudo, criado_em
FROM arquivos_conteudo
WHERE arquivo_id = $1
AND metodo = $2
`

type GetArquivoConteudoParams struct {
	ArquivoID int64
	Metodo    string
}

func (q *Queries) GetArquivoConteudo(ctx context.Context, arg GetArquivoConteudoParams) (ArquivoConteudo, error) {
	row := q.db.QueryRow(ctx, getArquivoConteudo, arg.ArquivoID, arg.Metodo)
	var i ArquivoConteudo
	err := row.Scan(
		&i.ID,
		&i.ArquivoID,
		&i.Metodo,
		&i.Formato,
		&i.Conteudo,
		&i.CriadoEm,
	)
	return i, err
}

const getArquivoConteudoLatest = `-- name: GetArquivoConteudoLatest :one
SELECT id, arquivo_id, metodo, formato, conteudo, criado_em
FROM arquivos_conteudo
WHERE arquivo_id = $1
ORDER BY criado_em DESC
LIMIT 1
`

func (q *Queries) GetArquivoConteudoLatest(ctx context.Context, arquivoID int64) (ArquivoConteudo, error) {
	row := q.db.QueryRow(ctx, getArquivoConteudoLatest, arquivoID)
	var i ArquivoConteudo
	err := row.Scan(
		&i.ID,
		&i.ArquivoID,
		&i.Metodo,
		&i.Formato,
		&i.Conteudo,
		&i.CriadoEm,
	)
	return i, err
}

const saveArquivo = `-- name: SaveArquivo :one
INSERT INTO arquivos (hash_sha256, chave_storage, mime_type, tamanho_bytes)
VALUES ($1, $2, $3, $4)
RETURNING id, hash_sha256, chave_storage, mime_type, tamanho_bytes, criado_em
`

type SaveArquivoParams struct {
	HashSHA256   []byte
	ChaveStorage string
	MimeType     string
	TamanhoBytes int64
}

func (q *Queries) SaveArquivo(ctx context.Context, arg SaveArquivoParams) (Arquivo, error) {
	row := q.db.QueryRow(ctx, saveArquivo,
		arg.HashSHA256,
		arg.ChaveStorage,
		arg.MimeType,
		arg.TamanhoBytes,
	)
	var i Arquivo
	err := row.Scan(
		&i.ID,
		&i.HashSHA256,
		&i.ChaveStorage,
		&i.MimeType,
		&i.TamanhoBytes,
		&i.CriadoEm,
	)
	return i, err
}

const saveArquivoConteudo = `-- name: SaveArquivoConteudo :one
INSERT INTO arquivos_conteudo (arquivo_id, metodo, formato, conteudo)
VALUES ($1, $2, $3, $4)
RETURNING id, arquivo_id, metodo, formato, conteudo, criado_em
`

type SaveArquivoConteudoParams struct {
	ArquivoID int64
	Metodo    string
	Formato   string
	Conteudo  string
}

func (q *Queries) SaveArquivoConteudo(ctx context.Context, arg SaveArquivoConteudoParams) (ArquivoConteudo, error) {
	row := q.db.QueryRow(ctx, saveArquivoConteudo,
		arg.ArquivoID,
		arg.Metodo,
		arg.Formato,
		arg.Conteudo,
	)
	var i ArquivoConteudo
	err := row.Scan(
		&i.ID,
		&i.ArquivoID,
		&i.Metodo,
		&i.Formato,
		&i.Conteudo,
		&i.CriadoEm,
	)
	return i, err
}

const saveArquivoConteudoChunk = `-- name: SaveArquivoConteudoChunk :exec
INSERT INTO arquivos_conteudo_chunks (conteudo_id, indice, conteudo, tokens, embedding)
VALUES ($1, $2, $3, $4, $5)
`

type SaveArquivoConteudoChunkParams struct {
	ConteudoID int64
	Indice     int32
	Conteudo   string
	Tokens     pgtype.Int4
	Embedding  pgvector.Vector
}

func (q *Queries) SaveArquivoConteudoChunk(ctx context.Context, arg SaveArquivoConteudoChunkParams) error {
	_, err := q.db.Exec(ctx, saveArquivoConteudoChunk,
		arg.ConteudoID,
		arg.Indice,
		arg.Conteudo,
		arg.Tokens,
		arg.Embedding,
	)
	return err
}
