// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Arquivo struct {
	Hash         string
	StorageKey   string
	ContentType  string
	TamanhoBytes int64
	CriadoEm     pgtype.Timestamptz
}

type DocumentoAnexo struct {
	IDProtocolo int64
	Hash        string
	BaixadoEm   pgtype.Timestamptz
}

type TokenChatbot struct {
	Hash         []byte
	Plataforma   string
	PlataformaID string
	ExpiraEm     pgtype.Timestamptz
}

type UsuarioChatbot struct {
	Plataforma   string
	PlataformaID string
	SEIUsuario   string
	SEISenha     []byte
	CriadoEm     pgtype.Timestamptz
	SEIOrgao     int32
}
