// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Token struct {
	Hash      []byte
	UsuarioID pgtype.UUID
	Escopo    string
	ExpiraEm  pgtype.Timestamptz
}

type Usuario struct {
	ID              pgtype.UUID
	Nome            string
	CPF             string
	Email           string
	EmailVerificado bool
	HashSenha       pgtype.Text
	CriadoEm        pgtype.Timestamptz
	AtualizadoEm    pgtype.Timestamptz
}
