// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Arquivo struct {
	ID           int64
	HashSHA256   []byte
	ChaveStorage string
	MimeType     string
	TamanhoBytes int64
	CriadoEm     pgtype.Timestamptz
}

type ArquivoConteudo struct {
	ID        int64
	ArquivoID int64
	Metodo    string
	Formato   string
	Conteudo  string
	CriadoEm  pgtype.Timestamptz
}

type ArquivoConteudoChunk struct {
	ID         int64
	ConteudoID int64
	Indice     int32
	Conteudo   string
	Tokens     pgtype.Int4
	Embedding  pgvector.Vector
	CriadoEm   pgtype.Timestamptz
}

type Token struct {
	Hash      []byte
	UsuarioID pgtype.UUID
	Escopo    string
	ExpiraEm  pgtype.Timestamptz
}

type TokenChatbot struct {
	Hash         []byte
	Plataforma   string
	PlataformaID string
	ExpiraEm     pgtype.Timestamptz
}

type Usuario struct {
	ID              pgtype.UUID
	Nome            string
	CPF             string
	Email           string
	EmailVerificado bool
	HashSenha       pgtype.Text
	CriadoEm        pgtype.Timestamptz
	AtualizadoEm    pgtype.Timestamptz
}

type UsuarioChatbot struct {
	Plataforma   string
	PlataformaID string
	SEIUsuario   string
	SEISenha     []byte
	CriadoEm     pgtype.Timestamptz
}
