// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUsuarioForToken = `-- name: GetUsuarioForToken :one
SELECT u.id, u.nome, u.cpf, u.email, u.email_verificado, u.hash_senha, u.criado_em, u.atualizado_em
FROM usuarios u
JOIN tokens t ON t.usuario_id = u.id
WHERE t.hash = $1
AND t.escopo = $2
AND t.expira_em > CURRENT_TIMESTAMP
`

type GetUsuarioForTokenParams struct {
	Hash   []byte
	Escopo string
}

// GetUsuarioForToken retorna o usuário dono de um determinado token que ainda não tenha expirado.
func (q *Queries) GetUsuarioForToken(ctx context.Context, arg GetUsuarioForTokenParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUsuarioForToken, arg.Hash, arg.Escopo)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.CPF,
		&i.Email,
		&i.EmailVerificado,
		&i.HashSenha,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const saveToken = `-- name: SaveToken :exec
INSERT INTO tokens (hash, usuario_id, escopo, expira_em)
VALUES ($1, $2, $3, $4)
`

type SaveTokenParams struct {
	Hash      []byte
	UsuarioID pgtype.UUID
	Escopo    string
	ExpiraEm  pgtype.Timestamptz
}

func (q *Queries) SaveToken(ctx context.Context, arg SaveTokenParams) error {
	_, err := q.db.Exec(ctx, saveToken,
		arg.Hash,
		arg.UsuarioID,
		arg.Escopo,
		arg.ExpiraEm,
	)
	return err
}
