// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuarios_chatbot.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTokenChatbot = `-- name: DeleteTokenChatbot :exec
DELETE FROM tokens_chatbot
WHERE hash = $1
`

func (q *Queries) DeleteTokenChatbot(ctx context.Context, hash []byte) error {
	_, err := q.db.Exec(ctx, deleteTokenChatbot, hash)
	return err
}

const deleteTokensChatbot = `-- name: DeleteTokensChatbot :exec
DELETE FROM tokens_chatbot
WHERE (plataforma = $1 AND plataforma_id = $2)
OR expira_em <= CURRENT_TIMESTAMP
`

type DeleteTokensChatbotParams struct {
	Plataforma   string
	PlataformaID string
}

func (q *Queries) DeleteTokensChatbot(ctx context.Context, arg DeleteTokensChatbotParams) error {
	_, err := q.db.Exec(ctx, deleteTokensChatbot, arg.Plataforma, arg.PlataformaID)
	return err
}

const getTokenChatbot = `-- name: GetTokenChatbot :one
SELECT hash, plataforma, plataforma_id, expira_em
FROM tokens_chatbot
WHERE hash = $1
AND expira_em > CURRENT_TIMESTAMP
`

func (q *Queries) GetTokenChatbot(ctx context.Context, hash []byte) (TokenChatbot, error) {
	row := q.db.QueryRow(ctx, getTokenChatbot, hash)
	var i TokenChatbot
	err := row.Scan(
		&i.Hash,
		&i.Plataforma,
		&i.PlataformaID,
		&i.ExpiraEm,
	)
	return i, err
}

const getUsuarioChatbot = `-- name: GetUsuarioChatbot :one
SELECT plataforma, plataforma_id, sei_usuario, sei_senha, criado_em, sei_orgao
FROM usuarios_chatbot
WHERE plataforma = $1
AND plataforma_id = $2
`

type GetUsuarioChatbotParams struct {
	Plataforma   string
	PlataformaID string
}

func (q *Queries) GetUsuarioChatbot(ctx context.Context, arg GetUsuarioChatbotParams) (UsuarioChatbot, error) {
	row := q.db.QueryRow(ctx, getUsuarioChatbot, arg.Plataforma, arg.PlataformaID)
	var i UsuarioChatbot
	err := row.Scan(
		&i.Plataforma,
		&i.PlataformaID,
		&i.SEIUsuario,
		&i.SEISenha,
		&i.CriadoEm,
		&i.SEIOrgao,
	)
	return i, err
}

const saveTokenChatbot = `-- name: SaveTokenChatbot :exec
INSERT INTO tokens_chatbot (hash, plataforma, plataforma_id, expira_em)
VALUES ($1, $2, $3, $4)
`

type SaveTokenChatbotParams struct {
	Hash         []byte
	Plataforma   string
	PlataformaID string
	ExpiraEm     pgtype.Timestamptz
}

func (q *Queries) SaveTokenChatbot(ctx context.Context, arg SaveTokenChatbotParams) error {
	_, err := q.db.Exec(ctx, saveTokenChatbot,
		arg.Hash,
		arg.Plataforma,
		arg.PlataformaID,
		arg.ExpiraEm,
	)
	return err
}

const saveUsuarioChatbot = `-- name: SaveUsuarioChatbot :exec
INSERT INTO usuarios_chatbot (plataforma, plataforma_id, sei_usuario, sei_senha, sei_orgao)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (plataforma, plataforma_id) DO UPDATE SET
    sei_usuario = EXCLUDED.sei_usuario,
    sei_senha = EXCLUDED.sei_senha,
    sei_orgao = EXCLUDED.sei_orgao
`

type SaveUsuarioChatbotParams struct {
	Plataforma   string
	PlataformaID string
	SEIUsuario   string
	SEISenha     []byte
	SEIOrgao     int32
}

func (q *Queries) SaveUsuarioChatbot(ctx context.Context, arg SaveUsuarioChatbotParams) error {
	_, err := q.db.Exec(ctx, saveUsuarioChatbot,
		arg.Plataforma,
		arg.PlataformaID,
		arg.SEIUsuario,
		arg.SEISenha,
		arg.SEIOrgao,
	)
	return err
}
